name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            swt-artifact: org.eclipse.swt.win32.win32.x86_64
          - os: ubuntu-latest
            swt-artifact: org.eclipse.swt.gtk.linux.x86_64
          - os: macos-13
            swt-artifact: org.eclipse.swt.cocoa.macosx.x86_64
          - os: macos-latest
            swt-artifact: org.eclipse.swt.cocoa.macosx.aarch64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B compile "-Dswt.artifactId=${{ matrix.swt-artifact }}" --file pom.xml
      shell: bash

    - name: Run tests
      run: mvn -B test "-Dswt.artifactId=${{ matrix.swt-artifact }}" --file pom.xml
      shell: bash
      continue-on-error: true

    - name: Package
      run: mvn -B package -DskipTests "-Dswt.artifactId=${{ matrix.swt-artifact }}" --file pom.xml
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: badpeggy-${{ matrix.os }}
        path: target/*.jar
        retention-days: 30
